import Head from "next/head";
import Team from "../../components/teams/Team";

// fetches data about all teams from /equipos
// Maps over it to create an array of objects with a params key for each team
export const getStaticPaths = async () => {
  const res = await fetch(`${process.env.host}/equipos`);
  const data = await res.json();

  const paths = data.data.map((team) => {
    return {
      params: { team: team.name.toString() },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

// fetches data about the team's historical matches and all teams and tournaments from the respective API endpoints.
// It returns an object with the teamMatches, allTeamData(list of teams), name(name of the selected team), and tournaments props.
export const getStaticProps = async (context) => {
  const name = context.params.team;
  const res = await fetch(`${process.env.host}/equipos/${name}/historial`);
  const data = await res.json();

  const response = await fetch(`${process.env.host}/equipos`);
  const allTeams = await response.json();

  const response2 = await fetch(`${process.env.host}/torneos`);
  const allTournaments = await response2.json();

  return {
    props: {
      teamMatches: data,
      allTeamData: allTeams,
      name: name,
      tournaments: allTournaments,
    },
  };
};

//  receives the props from getStaticProps, filters the team data to get the selected team, and renders a Head component with the team logo
export const Details = ({ teamMatches, allTeamData, name, tournaments }) => {
  const teamSelected = allTeamData.data.filter((team) => team.name === name);

  return (
    <>
      <Head>
        <title>{teamSelected[0].name}: Torneos de La Banda del Lobo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={teamSelected[0].logo} />
      </Head>
      <main>
        {/* sends team matches and the team selected to the Team component */}
        <Team matches={teamMatches} team={teamSelected} />
      </main>
    </>
  );
};

export default Details;
