import Head from "next/head";
import Link from "next/link";

export const getStaticProps = async () => {
  const response = await fetch("http://localhost:3001/equipos");
  const data = await response.json();
  return {
    props: {
      teams: data,
    },
  };
};

const Teams = ({ teams }) => {
  return (
    <>
      <Head>
        <title>Equipos de Torneos LBDL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img width='123rem' height='123rem' src="https://i.imgur.com/j6itbSk.png" />
      <h1>Equipos de La Banda del Lobo</h1>
      {teams.data.map((team) => (
        <Link href={`/teams/${team.name}`} key={team._id} className="teamItem">
          <h3>{team.name}</h3>
          <img src={team.logo} width="150rem" />
        </Link>
      ))}
    </>
  );
};

export default Teams;
