import Head from "next/head";
import Teams from "../components/teams/Teams";

export const getStaticProps = async () => {
  const response = await fetch(`${process.env.host}/equipos`);
  const data = await response.json();
  return {
    props: {
      teams: data,
    },
  };
};

const teamsScene = ({ teams }) => {
  return (
    <>
      <Head>
        <title>Equipos de Torneos LBDL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        width="123rem"
        height="123rem"
        src="https://i.imgur.com/j6itbSk.png"
      />
      <h1>Equipos de La Banda del Lobo</h1>
     <Teams teams={teams} />
    </>
  );
};

export default teamsScene;
