import React, { useState } from "react";
import Leaderboard from "../components/leaderboard/Leaderboard";
import LeaderboardFilter from "../components/leaderboard/LeaderboardFilter";
import Head from "next/head";

export const getStaticProps = async () => {
  const response = await fetch(`${process.env.host}/equipos`);
  const data = await response.json();

  const res = await fetch(`${process.env.host}/partidos`);
  const allMatches = await res.json();

  return {
    props: {
      teams: data,
      matches: allMatches,
    },
  };
};

const Ranking = ({ teams, matches }) => {
  const [year, setYear] = useState("2023");

  const filteringYear = (e) => {
    const year = e.target.value;
    setYear(year);

    year === "2023"
      ? console.log(year)
      : year === "2021"
      ? console.log(year)
      : year === "2020"
      ? console.log(year)
      : console.log(year);
  };

  return (
    <>
     <Head>
        <title>Ranking | Torneos de La Banda del Lobo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        src="https://i.imgur.com/efMVcQt.png"
        width="123rem"
        height="123rem"
      />
      <h1>Ranking</h1>
      <LeaderboardFilter year={year} filteringYear={filteringYear} />
      <Leaderboard teams={teams} matches={matches} />
    </>
  );
};

export default Ranking;
