import React, { useState } from "react";
import Head from "next/head";
import Leaderboard from "../../components/leaderboard/Leaderboard";
import Fixture from "../../components/leaderboard/Fixture";
import LeaderboardFilter from "../../components/leaderboard/LeaderboardFilter";
import Image from "next/image";

// fecthes all matches stored in /partidos
export const getStaticProps = async () => {
  const res = await fetch(`${process.env.host}/partidos`);
  const allMatches = await res.json();

  return {
    props: {
      matches: allMatches,
    },
  };
};

// displays a leaderboard and fixture for a tournament
const Ranking = ({ matches }) => {
  //  here we manage the state of the year and the matches displayed
  const [year, setYear] = useState("2023");
  const [tournamentMatches, setTournamentMatches] = useState(
    matches.data.filter((match) => match.year === "2023")
  );

  //  this called when the user changes the year in the dropdown
  //  then it updates the state and filters the matches accordingly
  const filteringYear = (e) => {
    const year = e.target.value;
    setYear(year);

    year === "2023"
      ? setTournamentMatches(
          matches.data.filter(
            (match) =>
              match.year === "2023" &&
              match.tournament.includes("Draft") === false
          )
        )
      : year === "2022"
      ? setTournamentMatches(
          matches.data.filter(
            (match) =>
              match.year === "2022" &&
              match.tournament.includes("Draft") === false
          )
        )
      : year === "2021"
      ? setTournamentMatches(
          matches.data.filter(
            (match) =>
              match.year === "2021" &&
              match.tournament.includes("Draft") === false
          )
        )
      : year === "2020"
      ? setTournamentMatches(
          matches.data.filter(
            (match) =>
              match.year === "2020" &&
              match.tournament.includes("Draft") === false
          )
        )
      : setTournamentMatches(
          matches.data.filter(
            (match) =>
              match.year === "2019" &&
              match.tournament.includes("Draft") === false
          )
        );
  };

  return (
    <>
      <Head>
        <title>Ranking | Torneos de La Banda del Lobo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          alt="ranking logo"
          src="https://i.imgur.com/efMVcQt.png"
          width="123"
          height="123"
        />
        <h1 style={{ fontSize: "64px" }}>Ranking</h1>
        {/* we pass the year and filteringYear function and filter the leaderboard */}
        <LeaderboardFilter year={year} filteringYear={filteringYear} />
        {/* then the filtered matches are sent to render the leaderboard */}
        <Leaderboard matches={tournamentMatches} />
        {/* here we also send the tournament matches to render the fixture of the leaderboard */}
        <Fixture matches={tournamentMatches} />
      </main>
    </>
  );
};

export default Ranking;
