import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Torneos de La Banda del Lobo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <img width='123rem' height='123rem' src="https://i.imgur.com/j6itbSk.png" />
        <h1>Torneos de La Banda del Lobo</h1>
      </main>
    </>
  )
}
