import Head from "next/head";
import TournamentStats from "../../components/tournaments/TournamentStats";
import TournamentMatches from "../../components/tournaments/TournamentMatches";
import Image from "next/image";

export const getStaticPaths = async () => {
  const res = await fetch(`${process.env.host}/torneos`);
  const data = await res.json();

  const paths = data.data.map((tournament) => {
    return {
      params: { tournament: tournament.name.toString() },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const name = context.params.tournament;
  const res = await fetch(`${process.env.host}/torneos/${name}/partidos`);
  const data = await res.json();

  const response = await fetch(`${process.env.host}/torneos`);
  const allTournaments = await response.json();
  const tournament = allTournaments.data.filter(
    (tournamentEl) => tournamentEl.name === name
  );

  return {
    props: {
      tournamentMatches: data,
      tournament: tournament,
    },
  };
};

const Details = ({ tournament, tournamentMatches }) => {
  return (
    <>
      <Head>
        <title>{tournament[0].name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={tournament[0].logo} />
      </Head>
      <main>
        <Image
          alt={tournament[0].name}
          width="169"
          height="169"
          src={tournament[0].logo}
        />
        <h1>{tournament[0].name}</h1>
        <TournamentStats
          tournament={tournament}
          tournamentMatches={tournamentMatches}
        />
        <TournamentMatches tournamentMatches={tournamentMatches} />
      </main>
    </>
  );
};

export default Details;
