import Head from "next/head";
import Link from "next/link";

export const getStaticProps = async () => {
  const response = await fetch("http://localhost:3001/torneos");
  const data = await response.json();
  return {
    props: {
      tournaments: data,
    },
  };
};

const Tournaments = ({ tournaments }) => {
  return (
    <>
      <Head>
        <title>Torneos de La Banda del Lobo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img width='123rem' height='123rem' src="https://i.imgur.com/j6itbSk.png" />
      <h1>Torneos de La Banda del Lobo</h1>
      {tournaments.data.map((tournament) => (
        <Link href={`/tournaments/${tournament.name}`} key={tournament._id} className="teamItem">
          <h3>{tournament.name}</h3>
          <img src={tournament.logo} width="150rem" />
        </Link>
      ))}
    </>
  );
};

export default Tournaments;
